### ISSUE TITLE
hiffy call to SpRot.read_caboose_region does not work at all now

### ISSUE THREAD

**Issue by jclulow** [oxidecomputer/humility#412]
This used to work, and does not seem to anymore:

```
$ pfexec humility hiffy -c SpRot.caboose_size -a slot=A
humility: attached to 0483:3754:001200334741500820383733 via ST-Link V3
SpRot.caboose_size() => 0xf8

$ pfexec humility hiffy -c SpRot.read_caboose_region -n $(( 0xf8 )) -o /tmp/cab -a offset=0 -a slot=A
humility: attached to 0483:3754:001200334741500820383733 via ST-Link V3
thread 'main' panicked at 'source slice length (251) does not match destination slice length (248)', humility-hiffy/src/lib.rs:1239:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ humility --version
humility 0.10.27

$ pfexec humility hiffy -c SpRot.caboose_size -a slot=B
humility: attached to 0483:3754:001200334741500820383733 via ST-Link V3
SpRot.caboose_size() => 0xf8

$ pfexec humility hiffy -c SpRot.read_caboose_region -n $(( 0xf8 )) -o /tmp/cab -a offset=0 -a slot=B
humility: attached to 0483:3754:001200334741500820383733 via ST-Link V3
thread 'main' panicked at 'source slice length (251) does not match destination slice length (248)', humility-hiffy/src/lib.rs:1239:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ pfexec humility hiffy -c SpRot.read_caboose_region -n $(( 0xf8 - 1 )) -o /tmp/cab -a offset=0 -a slot=B
humility: attached to 0483:3754:001200334741500820383733 via ST-Link V3
thread 'main' panicked at 'source slice length (250) does not match destination slice length (247)', humility-hiffy/src/lib.rs:1239:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ pfexec humility hiffy -c SpRot.read_caboose_region -n 280 -o /tmp/cab -a offset=0 -a slot=B
humility: attached to 0483:3754:001200334741500820383733 via ST-Link V3
SpRot.read_caboose_region() => Err(<Complex error: RawCabooseOrSprotError>)
Wrote 280 bytes to '/tmp/cab'

$ od -c /tmp/cab
0000000  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0
*
0000420  \0  \0  \0  \0  \0  \0  \0  \0
0000430

$ pfexec humility hiffy -c SpRot.read_caboose_region -n 251 -o /tmp/cab -a offset=0 -a slot=B
humility: attached to 0483:3754:001200334741500820383733 via ST-Link V3
SpRot.read_caboose_region() => Err(<Complex error: RawCabooseOrSprotError>)
Wrote 251 bytes to '/tmp/cab'

$ od -c /tmp/cab
0000000  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0
*
0000360  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0  \0
0000373
```

Note in the past we were subtracting one from the value we got back from `SpRot.caboose_size` to pass as the lease length to `SpRot.read_caboose_region` due to oxidecomputer/hubris#1436.  I'm not sure if the fix for that is related to this or not, but as you can see above, I have tried a variety of lengths both shorter and longer and things seem quite confused.

**Comment by jclulow** [comment]
If it helps, we're using these images on this Gimlet:

```
    |O|  * SHA-1 digest of "/data/local/images/gimlet/rot/bootleby-v1.1.0-staging-dev-gimlet-onlydev.zip": 823eeab5d455853574b0f48ae6a1a0c574622417
    |O|
    |O|  * SHA-1 digest of "/data/local/images/gimlet/rot/build-gimlet-rot-image-a-cert-staging-dev-v1.0.0.zip": 2d8dcb028350ba1cf0e35e9bcae81ca3d2e6c23a
    |O|  * image "/data/local/images/gimlet/rot/build-gimlet-rot-image-a-cert-staging-dev-v1.0.0.zip" is:
    |O|      version => hubris build archive v8
    |O|      git rev => ec0b7fe84e51e6d320556380a6f1dbb464ab9647
    |O|     image id => [e, ea, f1, 1c, 33, fc, a2, 5b]
    |O|        board => oxide-rot-1
    |O|         name => oxide-rot-1
    |O|        image => a
    |O|       target => thumbv8m.main-none-eabihf
    |O|     features => dice-mfg
    |O|   total size => 174K
    |O|  kernel size => 60K
    |O|        tasks => 9
    |O|
    |O|  * SHA-1 digest of "/data/local/images/gimlet/rot/build-gimlet-rot-image-b-cert-staging-dev-v1.0.0.zip": 57af44fcee96272700a67e249841f9776150d1ad
    |O|  * image "/data/local/images/gimlet/rot/build-gimlet-rot-image-b-cert-staging-dev-v1.0.0.zip" is:
    |O|      version => hubris build archive v8
    |O|      git rev => ec0b7fe84e51e6d320556380a6f1dbb464ab9647
    |O|     image id => [f0, 59, 68, cc, cb, b6, 51, 9a]
    |O|        board => oxide-rot-1
    |O|         name => oxide-rot-1
    |O|        image => b
    |O|       target => thumbv8m.main-none-eabihf
    |O|     features => dice-mfg
    |O|   total size => 174K
    |O|  kernel size => 60K
    |O|        tasks => 9
```

```
    |O|  * image "/data/local/images/gimlet/c/sp/build-gimlet-c-lab-image-default.zip" is:
    |O|      git rev => a096c4c17b17772c72dbfb03e0b9c96e59d9a0fe
    |O|     image id => [f, b6, fe, d8, 3c, 51, f1, ed]
```
